export const NETWORKS = {
  DEFAULT: 57073,
  INKMAINNET: 57073,
  SONEIUMMAINNET: 1868,
  ABSTRACTMAINNET: 2741,
  BERA: 80094,
  UNICHAIN: 130,
  COTI: 2632500,
  ZORA: 7777777,
  PLUMEMAINNET: 98865,
  APE: 33139,
  CZ: 56,
  BASE: 8453,
  SONICMAINNET: 146,
  FORM: 478,
  SCROLL: 534352,
  BLAST: 81457,
  TAIKO: 167000,
  POLY: 137,
  HEMI: 43111,
  CREATOR_CHAIN: 66665,
  MONAD: 10143,
  NEXUS: 393,
  MEGA: 6342,
  TABI_V2: 9788,
  ATHENE: 281123,
  XRP: 1440002,
  SAHARA: 313313,
} as const;

export type TLD = {
  chainId: number;
  label: string;
  tld: string;
};

export const tlds: TLD[] = [
  { chainId: NETWORKS.BERA, label: 'honey', tld: 'honey' },
  { chainId: NETWORKS.CZ, label: 'cz', tld: 'cz' },
  { chainId: NETWORKS.INKMAINNET, label: 'ink', tld: 'ink' },
  { chainId: NETWORKS.ZORA, label: 'gold', tld: 'gold' },
  { chainId: NETWORKS.BASE, label: 'boss', tld: 'boss' },
  { chainId: NETWORKS.SONICMAINNET, label: 'speed', tld: 'speed' },
  { chainId: NETWORKS.ABSTRACTMAINNET, label: 'abs', tld: 'abs' },
  { chainId: NETWORKS.SONEIUMMAINNET, label: 'future', tld: 'future' },
  { chainId: NETWORKS.PLUMEMAINNET, label: 'goon', tld: 'goon' },
  { chainId: NETWORKS.FORM, label: 'form', tld: 'form' },
  { chainId: NETWORKS.SCROLL, label: 'scroll', tld: 'scroll' },
  { chainId: NETWORKS.BLAST, label: 'blast', tld: 'blast' },
  { chainId: NETWORKS.TAIKO, label: '🥁', tld: '%f0%9f%a5%81' },
  { chainId: NETWORKS.POLY, label: 'poly', tld: 'poly' },
  { chainId: NETWORKS.UNICHAIN, label: 'defi', tld: 'defi' },
  { chainId: NETWORKS.COTI, label: 'coti', tld: 'coti' },
  { chainId: NETWORKS.APE, label: 'ape', tld: 'ape' },
  { chainId: NETWORKS.HEMI, label: 'hvm', tld: 'hvm' },
  { chainId: NETWORKS.CREATOR_CHAIN, label: 'ceo', tld: 'ceo' },
  { chainId: NETWORKS.MONAD, label: 'mnd', tld: 'mnd' },
  { chainId: NETWORKS.NEXUS, label: 'nexus', tld: 'nexus' },
  { chainId: NETWORKS.MEGA, label: 'mega', tld: 'mega' },
  { chainId: NETWORKS.TABI_V2, label: 'tabi', tld: 'tabi' },
  { chainId: NETWORKS.ATHENE, label: 'athene', tld: 'athene' },
  { chainId: NETWORKS.XRP, label: 'xrp', tld: 'xrp' },
  { chainId: NETWORKS.SAHARA, label: 'sahara', tld: 'sahara' },
];
